/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aloomni202557201001;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import javax.swing.UIManager;

/**
 *
 * @author achmad_khusnul_yakin
 */
public class frameDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frameDashboard.class.getName());
    private String halamanAktif = "";
    private CardLayout cardLayout;
    /**
     * Creates new form frameDashboard
     */
    public frameDashboard() {
        initComponents();
        halamanAktif = "dashboard";
        inisialisasiPanel();
    }
    
    void inisialisasiPanel() {
        cardLayout = (CardLayout)panelContent.getLayout();
        panelContent.add(new panelDashboard(), "dashboard");
        panelContent.add(new panelJurusan(), "jurusan");
        panelContent.add(new panelGuru(), "guru");
        panelContent.add(new panelKelas(), "kelas");
        panelContent.add(new panelSiswa(), "siswa");
        panelContent.add(new panelAbout(), "about");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSidebar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bDashboard = new javax.swing.JButton();
        bJurusan = new javax.swing.JButton();
        bGuru = new javax.swing.JButton();
        bKelas = new javax.swing.JButton();
        bSiswa = new javax.swing.JButton();
        bAbout = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        panelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Aloomni");
        setAutoRequestFocus(false);
        setMaximumSize(new java.awt.Dimension(961, 604));
        setMinimumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        panelSidebar.setBackground(new java.awt.Color(0, 153, 255));
        panelSidebar.setPreferredSize(new java.awt.Dimension(250, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-mortarboard-40.png"))); // NOI18N
        jLabel1.setText("Aloomni");
        jLabel1.setIconTextGap(10);

        bDashboard.setBackground(new java.awt.Color(0, 153, 255));
        bDashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bDashboard.setForeground(new java.awt.Color(255, 255, 255));
        bDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-adventures-30.png"))); // NOI18N
        bDashboard.setText("Dashboard");
        bDashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bDashboard.setIconTextGap(10);
        bDashboard.addActionListener(this::bDashboardActionPerformed);

        bJurusan.setBackground(new java.awt.Color(0, 153, 255));
        bJurusan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bJurusan.setForeground(new java.awt.Color(255, 255, 255));
        bJurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-department-30.png"))); // NOI18N
        bJurusan.setText("Jurusan");
        bJurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bJurusan.setIconTextGap(10);
        bJurusan.addActionListener(this::bJurusanActionPerformed);

        bGuru.setBackground(new java.awt.Color(0, 153, 255));
        bGuru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bGuru.setForeground(new java.awt.Color(255, 255, 255));
        bGuru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-training-30.png"))); // NOI18N
        bGuru.setText("Guru");
        bGuru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bGuru.setIconTextGap(10);
        bGuru.addActionListener(this::bGuruActionPerformed);

        bKelas.setBackground(new java.awt.Color(0, 153, 255));
        bKelas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bKelas.setForeground(new java.awt.Color(255, 255, 255));
        bKelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-stocks-30.png"))); // NOI18N
        bKelas.setText("Kelas");
        bKelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bKelas.setIconTextGap(10);
        bKelas.addActionListener(this::bKelasActionPerformed);

        bSiswa.setBackground(new java.awt.Color(0, 153, 255));
        bSiswa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bSiswa.setForeground(new java.awt.Color(255, 255, 255));
        bSiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-customer-30.png"))); // NOI18N
        bSiswa.setText("Siswa");
        bSiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bSiswa.setIconTextGap(10);
        bSiswa.addActionListener(this::bSiswaActionPerformed);

        bAbout.setBackground(new java.awt.Color(0, 153, 255));
        bAbout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bAbout.setForeground(new java.awt.Color(255, 255, 255));
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-about-30.png"))); // NOI18N
        bAbout.setText("About");
        bAbout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bAbout.setIconTextGap(10);
        bAbout.addActionListener(this::bAboutActionPerformed);

        bLogout.setBackground(new java.awt.Color(0, 153, 255));
        bLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bLogout.setForeground(new java.awt.Color(255, 255, 255));
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-logout-30.png"))); // NOI18N
        bLogout.setText("Logout");
        bLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bLogout.setIconTextGap(10);
        bLogout.addActionListener(this::bLogoutActionPerformed);

        javax.swing.GroupLayout panelSidebarLayout = new javax.swing.GroupLayout(panelSidebar);
        panelSidebar.setLayout(panelSidebarLayout);
        panelSidebarLayout.setHorizontalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSidebarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addComponent(bDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bGuru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bKelas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bSiswa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bAbout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelSidebarLayout.setVerticalGroup(
            panelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSidebarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addComponent(bDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bGuru, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        getContentPane().add(panelSidebar, java.awt.BorderLayout.WEST);

        panelContent.setBackground(new java.awt.Color(255, 255, 255));
        panelContent.setLayout(new java.awt.CardLayout());
        getContentPane().add(panelContent, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDashboardActionPerformed
        // TODO add your handling code here:
        if (halamanAktif.equals("dashboard")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Anda sudah berada di halaman Dashboard");
            return;
        }
        halamanAktif = "dashboard";
        cardLayout.show(panelContent, "dashboard");
        
    }//GEN-LAST:event_bDashboardActionPerformed

    private void bJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJurusanActionPerformed
        // TODO add your handling code here:
        if (halamanAktif.equals("jurusan")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Anda sudah berada di halaman Jurusan");
            return;
        }
        halamanAktif = "jurusan";
        cardLayout.show(panelContent, "jurusan");
    }//GEN-LAST:event_bJurusanActionPerformed

    private void bGuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuruActionPerformed
        // TODO add your handling code here:
        if (halamanAktif.equals("guru")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Anda sudah berada di halaman Guru");
            return;
        }
        halamanAktif = "guru";
        cardLayout.show(panelContent, "guru");
    }//GEN-LAST:event_bGuruActionPerformed

    private void bKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKelasActionPerformed
        // TODO add your handling code here:
        if (halamanAktif.equals("kelas")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Anda sudah berada di halaman Kelas");
            return;
        }
        halamanAktif = "kelas";
        cardLayout.show(panelContent, "kelas");
    }//GEN-LAST:event_bKelasActionPerformed

    private void bSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSiswaActionPerformed
        // TODO add your handling code here:
        if (halamanAktif.equals("siswa")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Anda sudah berada di halaman Siswa");
            return;
        }
        halamanAktif = "siswa";
        cardLayout.show(panelContent, "siswa");
    }//GEN-LAST:event_bSiswaActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
        // TODO add your handling code here:
        if (halamanAktif.equals("about")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Anda sudah berada di halaman About");
            return;
        }
        halamanAktif = "about";
        cardLayout.show(panelContent, "about");
    }//GEN-LAST:event_bAboutActionPerformed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        // TODO add your handling code here:
        int pilih = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
        );

        if (pilih == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_bLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.put("Button.borderWidth", 0);
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e) {
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frameDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bDashboard;
    private javax.swing.JButton bGuru;
    private javax.swing.JButton bJurusan;
    private javax.swing.JButton bKelas;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bSiswa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelContent;
    private javax.swing.JPanel panelSidebar;
    // End of variables declaration//GEN-END:variables
}
